import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

// SearchBox.js
// @ts-ignore
import React, { getServerSideProps } from 'react';

const SearchBox = () => {
  const [query, setQuery] = getServerSideProps('');

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    // 构建要搜索的查询字符串
    const searchQuery = encodeURIComponent(query);
    // 重定向到指定的 URL，并附加搜索查询
    window.location.href = `https://chromewebstore.google.com/search/?q=${searchQuery}`;
  }; 
  return (<form onSubmit={handleSubmit} className="flex">      <input type="text" value={query} onChange={(e) => setQuery(e.target.value)} className="flex-1 mr-2 border p-2 rounded focus:outline-none focus:border-blue-300" placeholder="搜索豆瓣..." />      <button type="submit" className="bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600">        搜索      </button>    </form>);
}; 
